### ISSUE TITLE
Issue with tmp.srt

### ISSUE THREAD

**Issue by BEST8OY** [foocaaat/anki-watch#1]
Hello
Thanks for this nice addons.
Really nice tool for enhancing language listening.
 ---
There is an issue with turn new video into SRS.
It says this.
`Errno 2\] No such file or directory: ‘'D:/New folder\\stamp/tmp.srt`

I renamed my MKV file external sub to tmp.srt and putted it in stamp folder then it worked.
Is this how it supposed to be?

And can you make it so that it doesn't auto start "turn new video into SRS" in Anki startup?

**Comment by foocaaat** [comment]
**Hello,**
thanks for point that out, and no it doesn't suppose to do that.
after you pointed that out I have fixed that issue with the new update.
also removed the auto start thingy because it actually was annoying.

thanks for the issue,
really really glad the add-on helped someone other than myself.
